Error

diff --git a/.github/workflows/workflow2.yml b/.github/workflows/workflow2.yml
--- a/.github/workflows/workflow2.yml
+++ b/.github/workflows/workflow2.yml
@@ -17,6 +17,8 @@ jobs:
     steps:
       # Check-out your repository
       - uses: actions/checkout@v3
+      - name: To  show Error
+        run: echo "should fail at this point .." ; exit 1
       - name: Run a one-line script
         run: echo "Continuous Integration"
       
